#!/bin/sh /etc/rc.common
# Copyright 2023-2024 sirpdboy team <herboy2008@gmail.com>

START=99
STOP=15
EXTRA_COMMANDS='reset'
EXTRA_HELP="        reset   Reset to default settings"

reset() {
rm -rf /etc/config/kucat
cat <<EOF  >/etc/config/kucat

config basic
	option gouser 'admin'
	option gohome 'overview'
	option setbar '1'
	option wizard '0'
	option bgqs '1'
	option gossr 'passwall'
	option dayword '0'
	option background '0'
	option bklock '1'
	option mode 'dark'
	option bkuse '1'
	option primary_rgbs_ts '0.1'
	option primary_rgbbody '248,248,248'
	option primary_opacity '0'
	option primary_rgbs '28,66,188'
	option primary_rgbm_ts '0.9'
	option primary_rgbm '20,109,179'
	option fontmode '0'
	option font_d '1.1rem'
	option font_z '0.92rem'
	option font_x '0.875rem'
	option tsoset '1'
	option dhcp_domain '1'

config theme
	option primary_rgbbody '33,45,60'
	option primary_rgbs '76,157,69'
	option remarks '隔栏经典蓝色'
	option primary_opacity '0'
	option primary_rgbm_ts '0.9'
	option bkuse '1'
	option primary_rgbs_ts '0.1'
	option mode 'auto'
	option use '1'
	option primary_rgbm 'blue'

config theme
	option primary_rgbbody '33,45,60'
	option primary_rgbs '76,157,69'
	option primary_rgbm_ts '0.95'
	option primary_opacity '0'
	option bkuse '1'
	option remarks '无隔栏清爽绿'
	option primary_rgbs_ts '0'
	option mode 'dark'
	option use '1'
	option primary_rgbm 'green'

config theme
	option primary_rgb_ts '0.3'
	option primary_rgbm '26,131,97'
	option primary_rgbs '76 157 69'
	option bkuse '1'
	option remarks '无隔栏绿'
	option primary_rgbs_ts '0'
	option primary_opacity '10'
	option primary_rgbm_ts '0.5'
	option mode 'dark'
	option use '0'

config theme
	option primary_rgbm '66,139,139'
	option primary_rgbs 'rgb(55,103,128)'
	option mode 'light'
	option primary_opacity '0'
	option primary_rgbs_ts '0.1'
	option primary_rgbm_ts '1'
	option remarks '隔栏无背景蓝'
	option bkuse '0'
	option use '0'

config theme
	option primary_rgbm '50 67 77'
	option primary_rgbs 'rgb(64, 68, 70)'
	option primary_opacity '0'
	option primary_rgbs_ts '0'
	option remarks '灰无隔栏无背景'
	option bkuse '0'
	option primary_rgbm_ts '0.95'
	option mode 'auto'
	option use '0'

config theme
	option bkuse '1'
	option mode 'dark'
	option primary_rgbm '50 66 77'
	option primary_rgbs '55 80 90'
	option remarks '炫灰隔栏模糊'
	option primary_rgbs_ts '0'
	option use '0'
	option primary_rgbm_ts '0.5'
	option primary_opacity '10'

config theme
	option mode 'light'
	option primary_rgbm '74,161,133'
	option primary_rgbs '76 157 69'
	option primary_rgbs_ts '0.2'
	option remarks '炫绿隔栏模糊'
	option primary_rgbm_ts '0.5'
	option bkuse '1'
	option primary_opacity '10'
	option use '0'



EOF
}


kucatset(){
sum=$(grep -c 'theme' /etc/config/kucat)
useset=0
for i in $(seq 0 $((sum-1)))
do
    use=$(uci -q get kucat.@theme[$i].use )
    
    if [ "x$use" == "x1" ]; then
	mode=`uci -q get kucat.@theme[$i].mode`
	primary_rgbm=`uci -q get kucat.@theme[$i].primary_rgbm`
	uci set kucat.@basic[0].mode=${mode}
	case "$primary_rgbm" in
		blue)
			uci set kucat.@basic[0].primary_rgbm='20,109,179'
			uci set kucat.@basic[0].bkuse=`uci -q get kucat.@theme[$i].bkuse`
			uci set kucat.@basic[0].primary_rgbm_ts='0.9'
			uci set kucat.@basic[0].primary_opacity='0'
			uci set kucat.@basic[0].primary_rgbs_ts=`uci -q get kucat.@theme[$i].primary_rgbs_ts`
			uci set kucat.@basic[0].primary_rgbs='28,66,188'
 			[ $mode = dark ] && uci set kucat.@basic[0].primary_rgbbody='33,45,60' || uci set kucat.@basic[0].primary_rgbbody='248,248,248'
		;;
		green)
			uci set kucat.@basic[0].bkuse=`uci -q get kucat.@theme[$i].bkuse`
			uci set kucat.@basic[0].primary_rgbm_ts='0.9'
			uci set kucat.@basic[0].primary_opacity='0'
			uci set kucat.@basic[0].primary_rgbm='26,131,97'
			uci set kucat.@basic[0].primary_rgbs_ts=`uci -q get kucat.@theme[$i].primary_rgbs_ts`
			uci set kucat.@basic[0].primary_rgbs='76,157,69'
 			[ $mode = dark ] && uci set kucat.@basic[0].primary_rgbbody='33,45,60' || uci set kucat.@basic[0].primary_rgbbody='248,248,248'
		;;
		orange)
			uci set kucat.@basic[0].bkuse=`uci -q get kucat.@theme[$i].bkuse`
			uci set kucat.@basic[0].primary_rgbm_ts='0.9'
			uci set kucat.@basic[0].primary_opacity='0'
			uci set kucat.@basic[0].primary_rgbm='163,71,6'
			uci set kucat.@basic[0].primary_rgbs_ts=`uci -q get kucat.@theme[$i].primary_rgbs_ts`
			uci set kucat.@basic[0].primary_rgbs='142,93,8'
		;;
		red)
			uci set kucat.@basic[0].bkuse=`uci -q get kucat.@theme[$i].bkuse`
			uci set kucat.@basic[0].primary_rgbm_ts='0.9'
			uci set kucat.@basic[0].primary_opacity='0'
			uci set kucat.@basic[0].primary_rgbm='143,32,13'
			uci set kucat.@basic[0].primary_rgbs_ts=`uci -q get kucat.@theme[$i].primary_rgbs_ts`
			uci set kucat.@basic[0].primary_rgbs='243,119,72'
		;;
		black)
			uci set kucat.@basic[0].bkuse=`uci -q get kucat.@theme[$i].bkuse`
			uci set kucat.@basic[0].primary_rgbm_ts='0.95'
			uci set kucat.@basic[0].primary_opacity='0'
			uci set kucat.@basic[0].primary_rgbm='25,25,26'
			uci set kucat.@basic[0].primary_rgbs_ts=`uci -q get kucat.@theme[$i].primary_rgbs_ts`
			uci set kucat.@basic[0].primary_rgbs='55,80,90'
		;;
		gray)
			uci set kucat.@basic[0].bkuse=`uci -q get kucat.@theme[$i].bkuse`
			uci set kucat.@basic[0].primary_rgbm_ts='0.5'
			uci set kucat.@basic[0].primary_opacity='10'
			uci set kucat.@basic[0].primary_rgbm='50,67,77'
			uci set kucat.@basic[0].primary_rgbs_ts=`uci -q get kucat.@theme[$i].primary_rgbs_ts`
			uci set kucat.@basic[0].primary_rgbs='64,68,70'
		;;
		bluets)
			uci set kucat.@basic[0].bkuse=`uci -q get kucat.@theme[$i].bkuse`
			uci set kucat.@basic[0].primary_rgbm_ts='0.5'
			uci set kucat.@basic[0].primary_opacity='10'
			uci set kucat.@basic[0].primary_rgbm='66,139,139'
			uci set kucat.@basic[0].primary_rgbs_ts=`uci -q get kucat.@theme[$i].primary_rgbs_ts`
			uci set kucat.@basic[0].primary_rgbs='55,103,128'
		;;
		*)
			uci set kucat.@basic[0].bkuse=`uci -q get kucat.@theme[$i].bkuse`
			uci set kucat.@basic[0].primary_rgbm_ts=`uci -q get kucat.@theme[$i].primary_rgbm_ts`
			uci set kucat.@basic[0].primary_opacity=`uci -q get kucat.@theme[$i].primary_opacity`
			uci set kucat.@basic[0].primary_rgbm=`echo $primary_rgbm | sed 's#(##; s#)##g; s#rgb##g; s#\,\ #\,#g;s#\ #\,#g;'`
			uci set kucat.@basic[0].primary_rgbs=`uci -q get kucat.@theme[$i].primary_rgbs | sed 's#(##; s#)##g; s#rgb##g; s#\,\ #\,#g;s#\ #\,#g;'`
			uci set kucat.@basic[0].primary_rgbs_ts=`uci -q get kucat.@theme[$i].primary_rgbs_ts`
 		;;
	esac
	useset=1
	break
    fi
done
if [ "x$useset" == "x0" ] ; then
	uci set kucat.@basic[0].mode='auto'
	uci set kucat.@basic[0].primary_rgbm='74,161,133'
	uci set kucat.@basic[0].primary_rgbs_ts='0'
	uci set kucat.@basic[0].primary_rgbs='225,112,88'
	uci set kucat.@basic[0].bkuse='1'
	uci set kucat.@basic[0].primary_rgbm_ts='0.5'
	uci set kucat.@basic[0].primary_opacity='10'
fi
[ $mode == dark ] && uci set kucat.@basic[0].primary_rgbbody='33,45,60' || uci set kucat.@basic[0].primary_rgbbody='244,245,247'
case "x$(uci -q get kucat.@basic[0].fontmode)" in
	x1)
	uci set kucat.@basic[0].font_d='1.1rem'
	uci set kucat.@basic[0].font_z='0.92rem'
	uci set kucat.@basic[0].font_x='0.875rem'
	;;
	x2)
	uci set kucat.@basic[0].font_d='1.3rem'
	uci set kucat.@basic[0].font_z='1.1rem'
	uci set kucat.@basic[0].font_x='0.92rem'
	;;
	*)
	uci set kucat.@basic[0].font_d='1rem'
	uci set kucat.@basic[0].font_z='0.875rem'
	uci set kucat.@basic[0].font_x='0.82rem'
	;;
esac
uci commit kucat
}

start() {
    [ "x$(uci -q get kucat.@basic[0].mode)" = "x" ]  && /etc/config/kucat reset 
    kucatset
    rm -rf /tmp/luci-*
}

stop() {
rm -rf /tmp/luci*
}


